
package org.koushik.javabrains;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidPropertyException", targetNamespace = "http://javabrains.koushik.org/")
public class InvalidPropertyException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidPropertyException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidPropertyException_Exception(String message, InvalidPropertyException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidPropertyException_Exception(String message, InvalidPropertyException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.koushik.javabrains.InvalidPropertyException
     */
    public InvalidPropertyException getFaultInfo() {
        return faultInfo;
    }

}
