
package org.koushik.javabrains;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShopInfo", targetNamespace = "http://javabrains.koushik.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShopInfo {


    /**
     * 
     * @param lookupInput
     * @return
     *     returns java.lang.String
     * @throws InvalidPropertyException_Exception
     */
    @WebMethod
    @WebResult(name = "lookupOutput", partName = "lookupOutput")
    @Action(input = "http://javabrains.koushik.org/ShopInfo/getShopInfoRequest", output = "http://javabrains.koushik.org/ShopInfo/getShopInfoResponse", fault = {
        @FaultAction(className = InvalidPropertyException_Exception.class, value = "http://javabrains.koushik.org/ShopInfo/getShopInfo/Fault/InvalidPropertyException")
    })
    public String getShopInfo(
            @WebParam(name = "lookupInput", partName = "lookupInput")
            String lookupInput)
        throws InvalidPropertyException_Exception
    ;

}
