
package org.koushik.javabrains;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShopInfoService", targetNamespace = "http://javabrains.koushik.org/", wsdlLocation = "http://vans-macbook-pro.local:8080/SOAP7_HandlingException/ShopInfoService?wsdl")
public class ShopInfoService
    extends Service
{

    private final static URL SHOPINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHOPINFOSERVICE_EXCEPTION;
    private final static QName SHOPINFOSERVICE_QNAME = new QName("http://javabrains.koushik.org/", "ShopInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://vans-macbook-pro.local:8080/SOAP7_HandlingException/ShopInfoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHOPINFOSERVICE_WSDL_LOCATION = url;
        SHOPINFOSERVICE_EXCEPTION = e;
    }

    public ShopInfoService() {
        super(__getWsdlLocation(), SHOPINFOSERVICE_QNAME);
    }

    public ShopInfoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHOPINFOSERVICE_QNAME, features);
    }

    public ShopInfoService(URL wsdlLocation) {
        super(wsdlLocation, SHOPINFOSERVICE_QNAME);
    }

    public ShopInfoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHOPINFOSERVICE_QNAME, features);
    }

    public ShopInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShopInfoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShopInfo
     */
    @WebEndpoint(name = "ShopInfoPort")
    public ShopInfo getShopInfoPort() {
        return super.getPort(new QName("http://javabrains.koushik.org/", "ShopInfoPort"), ShopInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShopInfo
     */
    @WebEndpoint(name = "ShopInfoPort")
    public ShopInfo getShopInfoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://javabrains.koushik.org/", "ShopInfoPort"), ShopInfo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHOPINFOSERVICE_EXCEPTION!= null) {
            throw SHOPINFOSERVICE_EXCEPTION;
        }
        return SHOPINFOSERVICE_WSDL_LOCATION;
    }

}
